language: ruby

services:
  - mysql
  - postgresql

rvm:
  - 2.5.7
  - 2.6.5

# Set as `export BUNDLE_GEMFILE=`pwd`/test/ci/railsXX.gemfile` before running tests
gemfile:
  - Gemfile
  - spec/ci/rails52.gemfile
  - spec/ci/rails50.gemfile

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql

script: 'bundle exec rake spec'

before_script:
  - bundle exec rake db:drop
  - bundle exec rake db:create
